services:
  mysql:
    image: mysql:8.0
    container_name: condominio-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: condominio
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
