/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciador.de.condominio.View;

import com.mycompany.gerenciador.de.condominio.Controllers.MoradorResidenciaController;
import com.mycompany.gerenciador.de.condominio.Controllers.PessoaController;
import com.mycompany.gerenciador.de.condominio.Controllers.ResidenciaController;
import com.mycompany.gerenciador.de.condominio.Models.Pessoa;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @author luis
 */
public class ListarMoradores extends javax.swing.JFrame {

    private final ResidenciaController rc;
    private final PessoaController pc;
    private final MoradorResidenciaController mrc;
    private JTable table;

    /**
     * Creates new form ListarMoradores
     */
    public ListarMoradores() throws SQLException {
        rc = new ResidenciaController();
        pc = new PessoaController();
        mrc = new MoradorResidenciaController();
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tableMoradoresResidencia.getModel();

        var moradorResidencia = pc.findAll();
        List<Pessoa> moradoresR = new ArrayList<>();
        for (var moradorR : moradorResidencia) {
            moradoresR.add(pc.findOne(moradorR.getId()));
        }

        moradoresR.forEach(morador -> {
            model.addRow(new Object[]{morador.getNome(), morador.getRg(), morador.getIdade()});
        });
        table = new JTable(model);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMoradoresResidencia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cepResidencia = new javax.swing.JTextField();
        buscarbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ruaResidencia = new javax.swing.JTextField();
        numResidencia = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadMorador = new javax.swing.JMenuItem();
        lisMorador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadResidencia = new javax.swing.JMenuItem();
        listResidencia = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableMoradoresResidencia.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String[]{
                        "Nome", "CPF", "Idade"
                }
        ));
        jScrollPane1.setViewportView(tableMoradoresResidencia);

        cepResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepResidenciaActionPerformed(evt);
            }
        });

        buscarbtn.setText("Buscar");
        buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("LISTAR MORADORES");

        jLabel3.setText("Número:");

        jLabel4.setText("Rua:");

        jLabel5.setText("CEP: ");

        jMenu1.setText("Moradores");

        cadMorador.setText("Cadastrar");
        jMenu1.add(cadMorador);

        lisMorador.setText("Listar");
        jMenu1.add(lisMorador);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Residências");

        cadResidencia.setText("Cadastrar");
        jMenu2.add(cadResidencia);

        listResidencia.setText("Listar");
        jMenu2.add(listResidencia);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pagamentos");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(181, 181, 181)
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(ruaResidencia))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel3))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(numResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cepResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(51, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(buscarbtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(numResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cepResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ruaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtnActionPerformed
        int numero = Integer.parseInt(numResidencia.getText());
        String cep = cepResidencia.getText();
        String rua = ruaResidencia.getText();
        DefaultTableModel model = (DefaultTableModel) tableMoradoresResidencia.getModel();
        model.setRowCount(0);
        try {
            var residencia = rc.findOne(numero, cep, rua);
            var moradorResidencia = mrc.findAll(residencia.getId());
            List<Pessoa> moradoresR = new ArrayList<>();
            for (var moradorR : moradorResidencia) {
                moradoresR.add(pc.findOne(moradorR.getMoradorId()));
            }
            moradoresR.forEach(morador -> {
                model.addRow(new Object[]{morador.getNome(), morador.getRg(), morador.getIdade()});
            });
            table = new JTable(model);

        } catch (SQLException ex) {
            Logger.getLogger(ListarMoradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarbtnActionPerformed

    private void cepResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepResidenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarMoradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarMoradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarMoradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarMoradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListarMoradores().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ListarMoradores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarbtn;
    private javax.swing.JMenuItem cadMorador;
    private javax.swing.JMenuItem cadResidencia;
    private javax.swing.JTextField cepResidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem lisMorador;
    private javax.swing.JMenuItem listResidencia;
    private javax.swing.JTextField numResidencia;
    private javax.swing.JTextField ruaResidencia;
    private javax.swing.JTable tableMoradoresResidencia;
    // End of variables declaration//GEN-END:variables
}
