/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciador.de.condominio.View;

import com.mycompany.gerenciador.de.condominio.Controllers.PagamentoResidenciaController;
import com.mycompany.gerenciador.de.condominio.Controllers.ResidenciaController;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis
 */
public class Pagamentos extends javax.swing.JFrame {
    private final ResidenciaController rc;
    private final PagamentoResidenciaController prc;
    private JTable table;
    /**
     * Creates new form Pagamentos
     */
    public Pagamentos() throws SQLException {
        rc = new ResidenciaController();
        prc = new PagamentoResidenciaController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numResidencia = new javax.swing.JTextField();
        textceo = new javax.swing.JLabel();
        cepResidencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ruaResidencia = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePagamento = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMorador = new javax.swing.JMenu();
        cadMorador = new javax.swing.JMenuItem();
        listMorador = new javax.swing.JMenuItem();
        menuResidencia = new javax.swing.JMenu();
        cadResidencia = new javax.swing.JMenuItem();
        listarResidencia = new javax.swing.JMenuItem();
        menuPagamento = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número:");

        numResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numResidenciaActionPerformed(evt);
            }
        });

        textceo.setText("CEP:");

        jLabel2.setText("Rua: ");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        tablePagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Status", "Valor", "Data"
            }
        ));
        jScrollPane1.setViewportView(tablePagamento);

        menuMorador.setText("Morador");

        cadMorador.setText("Cadastrar");
        menuMorador.add(cadMorador);

        listMorador.setText("Listar");
        menuMorador.add(listMorador);

        jMenuBar1.add(menuMorador);

        menuResidencia.setText("Residência");

        cadResidencia.setText("Cadastrar");
        menuResidencia.add(cadResidencia);

        listarResidencia.setText("Listar");
        menuResidencia.add(listarResidencia);

        jMenuBar1.add(menuResidencia);

        menuPagamento.setText("Pagamentos");
        jMenuBar1.add(menuPagamento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(textceo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cepResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ruaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(buscarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textceo)
                    .addComponent(cepResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ruaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numResidenciaActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        int numero = Integer.parseInt(numResidencia.getText());
        String cep = cepResidencia.getText();
        String rua = ruaResidencia.getText();
        DefaultTableModel model = (DefaultTableModel)tablePagamento.getModel();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        try {
            var residencia = rc.findOne(numero, cep, rua);
            var pagamentos = prc.fidnAll(residencia.getId());
            pagamentos.forEach(pagamento -> {
                String dataFormatada = pagamento.getData() != null ? pagamento.getData().format(formatter) : "";
                model.addRow(new Object[]{pagamento.getStatusPagamento(), pagamento.getValorPagamento(), dataFormatada});
            });
            
            table = new JTable(model);
        } catch (SQLException ex) {
            Logger.getLogger(Pagamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pagamentos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pagamentos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JMenuItem cadMorador;
    private javax.swing.JMenuItem cadResidencia;
    private javax.swing.JTextField cepResidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem listMorador;
    private javax.swing.JMenuItem listarResidencia;
    private javax.swing.JMenu menuMorador;
    private javax.swing.JMenu menuPagamento;
    private javax.swing.JMenu menuResidencia;
    private javax.swing.JTextField numResidencia;
    private javax.swing.JTextField ruaResidencia;
    private javax.swing.JTable tablePagamento;
    private javax.swing.JLabel textceo;
    // End of variables declaration//GEN-END:variables
}
